// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Phone_Market.Models;

public partial class Color
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}