// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Phone_Market.Models;

public partial class Receipt
{
    public int Id { get; set; }

    public Guid UserId { get; set; }

    public double TotalPrice { get; set; }

    public DateTimeOffset Date { get; set; }

    public virtual ICollection<OrderedItem> OrderedItems { get; set; } = new List<OrderedItem>();

    public virtual User User { get; set; }
}