// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Phone_Market.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public int RoleId { get; set; }

    public string Password { get; set; }

    public virtual ICollection<ProductRating> ProductRatings { get; set; } = new List<ProductRating>();

    public virtual ICollection<Receipt> Receipts { get; set; } = new List<Receipt>();

    public virtual Role Role { get; set; }

    public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; } = new List<ShoppingCart>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}